### ISSUE TITLE
createLoaderFunction does not exist

### ISSUE THREAD

**Issue by anonrig** [thomasheyenbrock/remix-graphql#11]
### Describe the bug

The documented createLoaderFunction on README does not exist on the code.

### Your Example Website or App

https://github.com/anonrig/bookclub

### Steps to Reproduce the Bug or Issue

The documented createLoaderFunction on README does not exist on the code.

### Expected behavior

The documented createLoaderFunction on README does not exist on the code.

### Javascript runtime version

18

### Deploy Target

Cloudflare Workers

### Operating System

macOS

**Comment by thomasheyenbrock** [comment]
Hey @anonrig 👋  thanks for reporting this! That's a typo in the readme, it's actually named `get` instead of `create`
